# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luo980/MyGits/AbilityFramework-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luo980/MyGits/AbilityFramework-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luo980/MyGits/AbilityFramework-cpp/CMakeFiles /home/luo980/MyGits/AbilityFramework-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luo980/MyGits/AbilityFramework-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Module_A

# Build rule for target.
Module_A: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Module_A
.PHONY : Module_A

# fast build rule for target.
Module_A/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Module_A.dir/build.make CMakeFiles/Module_A.dir/build
.PHONY : Module_A/fast

#=============================================================================
# Target rules for targets named ability_mgr

# Build rule for target.
ability_mgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ability_mgr
.PHONY : ability_mgr

# fast build rule for target.
ability_mgr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ability_mgr.dir/build.make CMakeFiles/ability_mgr.dir/build
.PHONY : ability_mgr/fast

#=============================================================================
# Target rules for targets named connection_mgr

# Build rule for target.
connection_mgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 connection_mgr
.PHONY : connection_mgr

# fast build rule for target.
connection_mgr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connection_mgr.dir/build.make CMakeFiles/connection_mgr.dir/build
.PHONY : connection_mgr/fast

#=============================================================================
# Target rules for targets named AbilityFramework

# Build rule for target.
AbilityFramework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AbilityFramework
.PHONY : AbilityFramework

# fast build rule for target.
AbilityFramework/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/build
.PHONY : AbilityFramework/fast

src/abilitymanager/abimanager.o: src/abilitymanager/abimanager.cpp.o
.PHONY : src/abilitymanager/abimanager.o

# target to build an object file
src/abilitymanager/abimanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ability_mgr.dir/build.make CMakeFiles/ability_mgr.dir/src/abilitymanager/abimanager.cpp.o
.PHONY : src/abilitymanager/abimanager.cpp.o

src/abilitymanager/abimanager.i: src/abilitymanager/abimanager.cpp.i
.PHONY : src/abilitymanager/abimanager.i

# target to preprocess a source file
src/abilitymanager/abimanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ability_mgr.dir/build.make CMakeFiles/ability_mgr.dir/src/abilitymanager/abimanager.cpp.i
.PHONY : src/abilitymanager/abimanager.cpp.i

src/abilitymanager/abimanager.s: src/abilitymanager/abimanager.cpp.s
.PHONY : src/abilitymanager/abimanager.s

# target to generate assembly for a file
src/abilitymanager/abimanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ability_mgr.dir/build.make CMakeFiles/ability_mgr.dir/src/abilitymanager/abimanager.cpp.s
.PHONY : src/abilitymanager/abimanager.cpp.s

src/connmanager/connmanager.o: src/connmanager/connmanager.cpp.o
.PHONY : src/connmanager/connmanager.o

# target to build an object file
src/connmanager/connmanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connection_mgr.dir/build.make CMakeFiles/connection_mgr.dir/src/connmanager/connmanager.cpp.o
.PHONY : src/connmanager/connmanager.cpp.o

src/connmanager/connmanager.i: src/connmanager/connmanager.cpp.i
.PHONY : src/connmanager/connmanager.i

# target to preprocess a source file
src/connmanager/connmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connection_mgr.dir/build.make CMakeFiles/connection_mgr.dir/src/connmanager/connmanager.cpp.i
.PHONY : src/connmanager/connmanager.cpp.i

src/connmanager/connmanager.s: src/connmanager/connmanager.cpp.s
.PHONY : src/connmanager/connmanager.s

# target to generate assembly for a file
src/connmanager/connmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connection_mgr.dir/build.make CMakeFiles/connection_mgr.dir/src/connmanager/connmanager.cpp.s
.PHONY : src/connmanager/connmanager.cpp.s

src/discoverymanager/audiodevs.o: src/discoverymanager/audiodevs.cpp.o
.PHONY : src/discoverymanager/audiodevs.o

# target to build an object file
src/discoverymanager/audiodevs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/audiodevs.cpp.o
.PHONY : src/discoverymanager/audiodevs.cpp.o

src/discoverymanager/audiodevs.i: src/discoverymanager/audiodevs.cpp.i
.PHONY : src/discoverymanager/audiodevs.i

# target to preprocess a source file
src/discoverymanager/audiodevs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/audiodevs.cpp.i
.PHONY : src/discoverymanager/audiodevs.cpp.i

src/discoverymanager/audiodevs.s: src/discoverymanager/audiodevs.cpp.s
.PHONY : src/discoverymanager/audiodevs.s

# target to generate assembly for a file
src/discoverymanager/audiodevs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/audiodevs.cpp.s
.PHONY : src/discoverymanager/audiodevs.cpp.s

src/discoverymanager/camdevs.o: src/discoverymanager/camdevs.cpp.o
.PHONY : src/discoverymanager/camdevs.o

# target to build an object file
src/discoverymanager/camdevs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/camdevs.cpp.o
.PHONY : src/discoverymanager/camdevs.cpp.o

src/discoverymanager/camdevs.i: src/discoverymanager/camdevs.cpp.i
.PHONY : src/discoverymanager/camdevs.i

# target to preprocess a source file
src/discoverymanager/camdevs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/camdevs.cpp.i
.PHONY : src/discoverymanager/camdevs.cpp.i

src/discoverymanager/camdevs.s: src/discoverymanager/camdevs.cpp.s
.PHONY : src/discoverymanager/camdevs.s

# target to generate assembly for a file
src/discoverymanager/camdevs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/camdevs.cpp.s
.PHONY : src/discoverymanager/camdevs.cpp.s

src/discoverymanager/discoverymanager.o: src/discoverymanager/discoverymanager.cpp.o
.PHONY : src/discoverymanager/discoverymanager.o

# target to build an object file
src/discoverymanager/discoverymanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/discoverymanager.cpp.o
.PHONY : src/discoverymanager/discoverymanager.cpp.o

src/discoverymanager/discoverymanager.i: src/discoverymanager/discoverymanager.cpp.i
.PHONY : src/discoverymanager/discoverymanager.i

# target to preprocess a source file
src/discoverymanager/discoverymanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/discoverymanager.cpp.i
.PHONY : src/discoverymanager/discoverymanager.cpp.i

src/discoverymanager/discoverymanager.s: src/discoverymanager/discoverymanager.cpp.s
.PHONY : src/discoverymanager/discoverymanager.s

# target to generate assembly for a file
src/discoverymanager/discoverymanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/discoverymanager.cpp.s
.PHONY : src/discoverymanager/discoverymanager.cpp.s

src/discoverymanager/dispdevs.o: src/discoverymanager/dispdevs.cpp.o
.PHONY : src/discoverymanager/dispdevs.o

# target to build an object file
src/discoverymanager/dispdevs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/dispdevs.cpp.o
.PHONY : src/discoverymanager/dispdevs.cpp.o

src/discoverymanager/dispdevs.i: src/discoverymanager/dispdevs.cpp.i
.PHONY : src/discoverymanager/dispdevs.i

# target to preprocess a source file
src/discoverymanager/dispdevs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/dispdevs.cpp.i
.PHONY : src/discoverymanager/dispdevs.cpp.i

src/discoverymanager/dispdevs.s: src/discoverymanager/dispdevs.cpp.s
.PHONY : src/discoverymanager/dispdevs.s

# target to generate assembly for a file
src/discoverymanager/dispdevs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/dispdevs.cpp.s
.PHONY : src/discoverymanager/dispdevs.cpp.s

src/discoverymanager/localhw_discovery.o: src/discoverymanager/localhw_discovery.cpp.o
.PHONY : src/discoverymanager/localhw_discovery.o

# target to build an object file
src/discoverymanager/localhw_discovery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/localhw_discovery.cpp.o
.PHONY : src/discoverymanager/localhw_discovery.cpp.o

src/discoverymanager/localhw_discovery.i: src/discoverymanager/localhw_discovery.cpp.i
.PHONY : src/discoverymanager/localhw_discovery.i

# target to preprocess a source file
src/discoverymanager/localhw_discovery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/localhw_discovery.cpp.i
.PHONY : src/discoverymanager/localhw_discovery.cpp.i

src/discoverymanager/localhw_discovery.s: src/discoverymanager/localhw_discovery.cpp.s
.PHONY : src/discoverymanager/localhw_discovery.s

# target to generate assembly for a file
src/discoverymanager/localhw_discovery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/discoverymanager/localhw_discovery.cpp.s
.PHONY : src/discoverymanager/localhw_discovery.cpp.s

src/eventhandler/eventhandler.o: src/eventhandler/eventhandler.cpp.o
.PHONY : src/eventhandler/eventhandler.o

# target to build an object file
src/eventhandler/eventhandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/eventhandler/eventhandler.cpp.o
.PHONY : src/eventhandler/eventhandler.cpp.o

src/eventhandler/eventhandler.i: src/eventhandler/eventhandler.cpp.i
.PHONY : src/eventhandler/eventhandler.i

# target to preprocess a source file
src/eventhandler/eventhandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/eventhandler/eventhandler.cpp.i
.PHONY : src/eventhandler/eventhandler.cpp.i

src/eventhandler/eventhandler.s: src/eventhandler/eventhandler.cpp.s
.PHONY : src/eventhandler/eventhandler.s

# target to generate assembly for a file
src/eventhandler/eventhandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/eventhandler/eventhandler.cpp.s
.PHONY : src/eventhandler/eventhandler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/plugincore/pluginload.o: src/plugincore/pluginload.cpp.o
.PHONY : src/plugincore/pluginload.o

# target to build an object file
src/plugincore/pluginload.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Module_A.dir/build.make CMakeFiles/Module_A.dir/src/plugincore/pluginload.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/plugincore/pluginload.cpp.o
.PHONY : src/plugincore/pluginload.cpp.o

src/plugincore/pluginload.i: src/plugincore/pluginload.cpp.i
.PHONY : src/plugincore/pluginload.i

# target to preprocess a source file
src/plugincore/pluginload.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Module_A.dir/build.make CMakeFiles/Module_A.dir/src/plugincore/pluginload.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/plugincore/pluginload.cpp.i
.PHONY : src/plugincore/pluginload.cpp.i

src/plugincore/pluginload.s: src/plugincore/pluginload.cpp.s
.PHONY : src/plugincore/pluginload.s

# target to generate assembly for a file
src/plugincore/pluginload.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Module_A.dir/build.make CMakeFiles/Module_A.dir/src/plugincore/pluginload.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AbilityFramework.dir/build.make CMakeFiles/AbilityFramework.dir/src/plugincore/pluginload.cpp.s
.PHONY : src/plugincore/pluginload.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AbilityFramework"
	@echo "... Module_A"
	@echo "... ability_mgr"
	@echo "... connection_mgr"
	@echo "... src/abilitymanager/abimanager.o"
	@echo "... src/abilitymanager/abimanager.i"
	@echo "... src/abilitymanager/abimanager.s"
	@echo "... src/connmanager/connmanager.o"
	@echo "... src/connmanager/connmanager.i"
	@echo "... src/connmanager/connmanager.s"
	@echo "... src/discoverymanager/audiodevs.o"
	@echo "... src/discoverymanager/audiodevs.i"
	@echo "... src/discoverymanager/audiodevs.s"
	@echo "... src/discoverymanager/camdevs.o"
	@echo "... src/discoverymanager/camdevs.i"
	@echo "... src/discoverymanager/camdevs.s"
	@echo "... src/discoverymanager/discoverymanager.o"
	@echo "... src/discoverymanager/discoverymanager.i"
	@echo "... src/discoverymanager/discoverymanager.s"
	@echo "... src/discoverymanager/dispdevs.o"
	@echo "... src/discoverymanager/dispdevs.i"
	@echo "... src/discoverymanager/dispdevs.s"
	@echo "... src/discoverymanager/localhw_discovery.o"
	@echo "... src/discoverymanager/localhw_discovery.i"
	@echo "... src/discoverymanager/localhw_discovery.s"
	@echo "... src/eventhandler/eventhandler.o"
	@echo "... src/eventhandler/eventhandler.i"
	@echo "... src/eventhandler/eventhandler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/plugincore/pluginload.o"
	@echo "... src/plugincore/pluginload.i"
	@echo "... src/plugincore/pluginload.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

