apiVersion: stable.example.com/v1
kind: SensorDevice
metadata:
  name: "DS18B20-temperature-sensor"
spec:
  kind: sensor
  version: "1.0"
  hostname: ""
  capability1:
    - name: ""
      api:
        - ""
  capability2:
    - name: ""
      api:
        - ""
  properties:
    location: unknown
    vendor: unknown
    interface: ""
status:
  occupancy: false
api:
  function:
    - name: "set_hand"
      param:
        - name: "void"
          type: "void"
          index: "1"
      returnparam:
        - name: "result"
          type: "uint8_t"
          index: "1"
    - name: "get_temperature"
      param:
        - name: "void"
          type: "void"
          index: "1"
      returnparam:
        - name: "result"
          type: "float"
          index: "1"
