apiVersion: stable.example.com/v1
kind: SensorDevice
metadata:
  name: "LD2410B-presence-sensor"
spec:
  kind: sensor
  version: "1.0"
  hostname: ""
  capability1:
    - name: ""
      api:
        - ""
  capability2:
    - name: ""
      api:
        - ""
  properties:
    location: unknown
    vendor: unknown
    interface: ""
status:
  occupancy: false
api:
  function:
    - name: "getDistance"
      param:
        - name: "distance"
          type: "uint16_t*"
          index: "1"
      returnparam:
        - name: "result"
          type: "uint8_t"
          index: "1"
