apiVersion: stable.example.com/v1
kind: SensorDevice
metadata:
  name: "testdemo6"
spec:
  kind: sensor
  version: "1.0"
  hostname: ""
  capability1:
    - name: temperature
      api:
        - Gettemperature
  capability2:
    - name: XiaomiTemperature
      api:
        - GetXiaomiTemperature
  properties:
    location: home
    vendor: oppo
    interface: standardinterface
status:
  occupancy: false
api:
  function:
    - name: Gettemperature
      param:
        - name: param1
          type: string
          index: "1"
        - name: param2
          type: string
          index: "2"
      returnparam:
        - name: param3
          type: string
          index: "1"
    - name: GetXiaomiTemperature
      param:
        - name: param1
          type: string
          index: "1"
        - name: param2
          type: string
          index: "2"
      returnparam:
        - name: param3
          type: string
          index: "1"
