apiVersion: "stable.example.com/v1"
kind: Ability
metadata:
  name: loudspeaker

level: "1"
abilityname: loudspeaker
description: this is a loudspeaker
followed: default
depends:
  abilities:
    - none
  devices:
    - speaker
spec:
  sampleRates: "16000"
  channelNumber: 8
  bitWidth: 16
  interface: standardinterface
ApiList:
  - ApiType: RPC
    ApiName: Open
    inputparam:
      - paramname: param1
        paramtype: string
        index: "1"
      - paramname: param2
        paramtype: string
        index: "2"
    returnparam:
      - paramname: param3
        paramtype: string
        index: "1"
  - ApiType: RPC
    ApiName: Close
    inputparam:
      - paramname: param1
        paramtype: string
        index: "1"
      - paramname: param2
        paramtype: string
        index: "2"
    returnparam:
      - paramname: param3
        paramtype: string
        index: "1"
  - ApiType: RPC
    ApiName: Play
    inputparam:
      - paramname: param1
        paramtype: string
        index: "1"
      - paramname: param2
        paramtype: string
        index: "2"
    returnparam:
      - paramname: param3
        paramtype: string
        index: "1"
  - ApiType: RPC
    ApiName: Configure
    inputparam:
      - paramname: param1
        paramtype: string
        index: "1"
      - paramname: param2
        paramtype: string
        index: "2"
    returnparam:
      - paramname: param3
        paramtype: string
        index: "1"