apiVersion: "stable.example.com/v1"
kind: Ability
metadata:
  name: sensor

level: "1"
abilityname: sensor
description: this is a sensor
followed: default
version: "1.0"
spec:
  location: home
  vendor: oppo
  interface: standardinterface
ApiList:
  - ApiType: RPC
    ApiName: open
    inputparam:
      - paramname: null
        paramtype: message
        index: "1"
    returnparam:
      - paramname: null
        paramtype: message
        index: "1"
  - ApiType: RPC
    ApiName: close
    inputparam:
      - paramname: null
        paramtype: message
        index: "1"
    returnparam:
      - paramname: null
        paramtype: message
        index: "1"
  - ApiType: RPC
    ApiName: read
    inputparam:
      - paramname: null
        paramtype: message
        index: "1"
    returnparam:
      - paramname: value
        paramtype: message
        index: "1"
  - ApiType: RPC
    ApiName: configure
    inputparam:
      - paramname: value
        paramtype: message
        index: "1"
    returnparam:
      - paramname: null
        paramtype: message
        index: "1"
