{
  goal:{
   Area: [x1, x2], [y1, y2], [z1, z2] 
   target: yellow_block
  },
  candidateAbilities:[
    {
      fixed_camera:{
        id: 0,
        fov: "90",
        focusMethod: FT,
        focus: 14mmstatus,
        location: [x,y,z]
      }
    },
    {
      mobile:{
        id: 1,
        wheel_r: 10cm,
        length: 40cm,
        width: 40cm,
        accessible_area: [x1, x2], [y1, y2], [z1, z2]
      },
      robot_camera:{
        id: 2,
        fov: "90",
        focusMethod: FT,
        focus: 14mmstatus,
        location: [x,y,z],
        accessible_area: [z1, z2]
      }
    }
  ]
}
