address : "mqtts://localhost:8883"
clientID : "camera_ability"
trustStore : "/home/zhuhz/ca_certs/rootCA.crt"
keyStore : "/home/zhuhz/ca_certs/client.crt"
privateKey : "/home/zhuhz/ca_certs/client.key"
username : "zhuhz"
password : "123456"
pipe : "../pipe/robot_status"
socket : "unix:/tmp/robot_command"