cameraOffset_x : 78.88
cameraOffset_z : -24.39999
fov : 26.99147
aspect : 1.333333
viewDistance : 500
map:
  - targetBox1:
      min:
        x: 540
        y: 210
        z: 790
      size:
        x: 20
        y: 20
        z: 20
  - targetBox2:
      min:
        x: 540
        y: 210
        z: 590
      size:
        x: 20
        y: 20
        z: 20