plugins:
  ability_mgr:
    enabled: true
    path: "/Users/luozhaoxin/Documents/AbilityFrameworkCpp/lib/modules"
  connection_mgr:
    enabled: true
    path: "/Users/luozhaoxin/Documents/AbilityFrameworkCpp/lib/modules"
  C:
    enabled: false
    path: "/Users/luozhaoxin/Documents/AbilityFrameworkCpp/lib/modules"
  D:
    enabled: true
    path: "/Users/luozhaoxin/Documents/AbilityFrameworkCpp/lib/modules"
