plugins:
  ability_mgr:
    enabled: true
    path: "./lib/modules"
  connection_mgr:
    enabled: true
    path: "./lib/modules"
  C:
    enabled: false
    path: "./lib/modules"
  D:
    enabled: true
    path: "./lib/modules"
